<div style="background: linear-gradient(120deg, #1a3a5c 0%, #2d6a9f 60%, #4a9eda 100%); padding: 28px 36px; border-radius: 14px; display: flex; align-items: center; gap: 28px; box-shadow: 0 4px 18px rgba(0,0,0,0.18);">
    <img src='Imagenes/iteso.jpg' style="height: 110px; border-radius: 8px; background: white; padding: 6px; flex-shrink: 0; box-shadow: 0 2px 8px rgba(0,0,0,0.2);"/>
    <div style="border-left: 2px solid rgba(255,255,255,0.4); padding-left: 28px;">
        <h1 style="margin: 0 0 8px 0; color: white; font-size: 1.5em; line-height: 1.3;">Propedéutico en Programación y Algoritmos para la Maestría en Ciencia de Datos</h1>
        <h3 style="margin: 0; color: rgba(255,255,255,0.8); font-weight: normal; font-size: 1.05em;">Módulo 2: Fundamentos de Numpy</h3>
    </div>
</div>


<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg" width="400px" height="400px" />

> Hasta ahora sólo hemos hablado acerca de tipos (clases) de variables y funciones que vienen por defecto en Python.

> Sin embargo, una de las mejores cosas de Python (especialmente si eres o te preparas para ser un científico de datos) es la gran cantidad de librerías de alto nivel que se encuentran disponibles.

> Algunas de estas librerías se encuentran en la librería estándar, es decir, se pueden encontrar donde sea que esté Python. Otras librerías se pueden añadir fácilmente.

> La primer librería externa que cubriremos en este curso es NumPy (Numerical Python).


Referencias:
- https://www.numpy.org/
- https://towardsdatascience.com/first-step-in-data-science-with-python-numpy-5e99d6821953
___

# 0. Motivación 

¿Recuerdan algo de álgebra lineal? Por ejemplo:
- vectores;
- suma de vectores;
- producto por un escalar ...

¿Cómo se les ocurre que podríamos manejar lo anterior en Python?

In [1]:
# Crear dos vectores
x = [1,2,3,4]
y = [2,5,7,8]
x+y

[1, 2, 3, 4, 2, 5, 7, 8]

In [66]:
# Suma de vectores


In [2]:
# ¿con ciclos quizá?
[x[i] + y[i] for i in range(len(x))]

[3, 7, 10, 12]

In [3]:
# Producto por escalar
3*x

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [4]:
# ¿con ciclos quizá?
[3*x[i] for i in range(len(x))]

[3, 6, 9, 12]

### Solución: NumPy

NumPy es la librería fundamental para computación científica con Python. Contiene, entre otros:
- una clase de objetos tipo arreglo N-dimensional muy poderso;
- funciones matemáticas sofisticadas;
- herramientas matemáticas útiles de álgebra lineal, transformada de Fourier y números aleatorios.

Aparte de sus usos científicos, NumPy puede ser usada como un contenedor eficiente de datos multidimensional, lo que le otorga a NumPy una capacidad impresionante de integración con bases de datos.

Por otra parte, casi todas las librerías de Python relacionadas con ciencia de datos y machine learning tales como SciPy (Scientific Python), Mat-plotlib (librería de gráficos), Scikit-learn, dependen de NumPy razonablemente.

Para nuestra fortuna, NumPy ya viene instalado por defecto en la instalación de Anaconda.

Así que si queremos empezar a utilizarlo, lo único que debemos hacer es importarlo:

In [6]:
pip install numpy

   ---------------------------------------- 0.0/12.5 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.5 MB 7.7 MB/s eta 0:00:02
   -------- ------------------------------- 2.6/12.5 MB 9.0 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.5 MB 9.4 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.5 MB 9.5 MB/s eta 0:00:01
   ------------------------ --------------- 7.6/12.5 MB 8.3 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.5 MB 8.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.5/12.5 MB 8.4 MB/s eta 0:00:01
   ---------------------------------------- 12.5/12.5 MB 8.0 MB/s  0:00:01
Note: you may need to restart the kernel to use updated packages.


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
#python -m pip install numpy

In [7]:
# Importar numpy
import numpy as np

In [8]:
np.pi

3.141592653589793

Lo que acabamos de hacer es un procedimiento genérico para importar librerías:
- se comienza con la palabra clave `import`;
- a continuación el nombre de la librería, en este caso `numpy`;
- opcionalmente se puede incluir una cláusula `as` y una abreviación del nombre de la librería. Para el caso de NumPy, la comunidad comúmente usa la abreviación `np`.

Ahora, intentemos hacer lo mismo que que antes, pero con el arreglo n-dimensional que provee NumPy como vector:

In [9]:
# Ayuda sobre arreglo N-dimensional
help(np.array)

Help on built-in function array in module numpy:

array(
    object,
    dtype=None,
    *,
    copy=True,
    order='K',
    subok=False,
    ndmin=0,
    ndmax=0,
    like=None
)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          ndmax=0, like=None)

    Create an array.

    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If ``True`` (default), then the array data is copied. If ``None``,
        a copy will only be made if ``__array__`` returns a copy, if 

In [10]:
# Crear dos vectores
x = np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [11]:
type(x)

numpy.ndarray

In [12]:
y = np.array([4,5,6,7,8])
y

array([4, 5, 6, 7, 8])

In [13]:
len(x), sum(x)

(5, np.int64(15))

In [14]:
# Suma de vectores
x + y

array([ 5,  7,  9, 11, 13])

In [15]:
# Producto interno
x.dot(y)

np.int64(100)

In [16]:
l1 = [1, 'x', False, min]
l1

[1, 'x', False, <function min>]

### Diferencias fundamentales entre Listas de Python y Arreglos de NumPy

Mientras que las listas y los arreglos tienen algunas similaridades (ambos son colecciones ordenadas de valores), existen ciertas diferencias abismales entre este tipo de estructuras de datos:

- A diferencia de las listas, todos los elementos en un arreglo de NumPy deben ser del mismo tipo de datos (esto es, todos enteros, o flotantes, o strings, etc).

- Por lo anterior, los arreglos de NumPy soportan operaciones aritméticas y otras funciones matemáticas que se ejecutan en cada elemento del arreglo. Las listas no soportan estos cálculos.

- Los arreglos de NumPy tienen dimensionalidad.

In [17]:
xx = np.array([[1,2,3],[2,3,4]])
xx

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
type(xx)

numpy.ndarray

In [ ]:
xx.ndim # Número de dimensiones

2

In [20]:
xx.shape # Dimensiones del arreglo

(2, 3)

In [21]:
xx = np.array([[[1,2,3],[2,3,4]]])

In [22]:
xx.ndim

3

# 1. ¿Qué podemos hacer en NumPy?

Ya vimos como crear arreglos básicos en NumPy, con el comando `np.array()`

¿Cuál es el tipo de estos arreglos?

In [23]:
type(x)

numpy.ndarray

También podemos crear arreglos multidimensionales:

In [31]:
# Matriz 4x5
xx = np.array([[1,2,3,2,1],
                [2,3,4,1,2], 
                [3,4,5,3,2], 
                [4,5,6,4,5]])
xx

array([[1, 2, 3, 2, 1],
       [2, 3, 4, 1, 2],
       [3, 4, 5, 3, 2],
       [4, 5, 6, 4, 5]])

In [32]:
# Tipo
xx.ndim

2

In [33]:
# Atributos - renglón , columna
xx.shape

(4, 5)

In [34]:
xx = np.array([[1,2,3],[2,3,4]])
xx

array([[1, 2, 3],
       [2, 3, 4]])

In [35]:
xx.shape

(2, 3)

In [36]:
print(xx)

[[1 2 3]
 [2 3 4]]


## 1.1 Funciones de NumPy

Seguiremos nuestra introducción a NumPy mediante la resolución del siguiente problema:

### Problema 1

> Dados cinco (5) contenedores cilíndricos con diferentes radios y alturas que pueden variar entre 5 y 25 cm, encontrar:
> 1. El volumen del agua que puede almacenar cada contenedor;
> 2. El volumen total del agua que pueden almacenar todos los contenedores juntos;
> 3. Cual contenedor puede almacenar más volumen, y cuanto;
> 4. Cual contenedor puede almacenar menos volumen, y cuanto;
> 5. Obtener la media, la mediana y la desviación estándar de los volúmenes de agua que pueden ser almacenados en los contenedores.

Antes que nada, definamos las variables que nos dan:

In [37]:
# Definir numero de contenedores, medida minima y medida maxima
n_contenedores = 5
medida_min = 5
medida_max = 25

A continuación, generaremos un arreglo de números enteros aleatorios entre 5 y 25 cm que representarán los radios y las alturas de los cilindros:

In [38]:
# Ayuda de np.random.randint()
help(np.random.randint)

Help on method randint in module numpy.random:

randint(low, high=None, size=None, dtype=<class 'int'>) method of numpy.random.mtrand.RandomState instance
    randint(low, high=None, size=None, dtype=int)

    Return random integers from `low` (inclusive) to `high` (exclusive).

    Return random integers from the "discrete uniform" distribution of
    the specified dtype in the "half-open" interval [`low`, `high`). If
    `high` is None (the default), then results are from [0, `low`).

    .. note::
        New code should use the `~numpy.random.Generator.integers`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    low : int or array-like of ints
        Lowest (signed) integers to be drawn from the distribution (unless
        ``high=None``, in which case this parameter is one above the
        *highest* such integer).
    high : int or array-like of ints, optional
        If provided, o

In [42]:
# Números aleatorios que representan radios y alturas.
# Inicializar la semilla
medidas = np.random.randint(medida_min, medida_max+1, size=(10)) #radios y alturas

In [43]:
# Ver valores
medidas

array([15,  5, 17, 19, 20,  6,  7, 23,  7, 22], dtype=int32)

In [44]:
# array.reshape
medidas.shape

(10,)

In [ ]:
#reshape
medidas = medidas.reshape(2,5) #filas, columnas = alturas, radios
medidas

array([[15,  5, 17, 19, 20],
       [ 6,  7, 23,  7, 22]], dtype=int32)

In [49]:
medidas.shape

(2, 5)

De los números generados, separemos los que corresponden a los radios, y los que corresponden a las alturas:

In [55]:
# Radios
radios = medidas[0]
radios

array([15,  5, 17, 19, 20], dtype=int32)

In [ ]:
medidas[0,1:4] #fila 1, columnas 1 a 3

array([ 5, 17, 19], dtype=int32)

In [57]:
# Alturas
alturas = medidas[1]
alturas

array([ 6,  7, 23,  7, 22], dtype=int32)

$$ V = \pi*r^2*h$$

1. Con lo anterior, calculemos cada uno los volúmenes:

In [59]:
volumenes = np.pi * (radios**2) * alturas

In [60]:
# Volúmenes de los contenedores
volumenes

array([ 4241.15008235,   549.77871438, 20882.16636841,  7938.80463562,
       27646.01535159])

<img style="float: right; margin: 0px 0px 15px 15px;" src="https://upload.wikimedia.org/wikipedia/commons/b/b3/Symbol_great.svg" width="400px" height="400px" />

### ¡Excelente!

Con esta línea de código tan sencilla, pudimos obtener de un solo jalón todos los volúmenes de nuestros contenedores.

Esta es la potencia que nos ofrece NumPy. Podemos operar los arreglos de forma rápida, sencilla, y muy eficiente.

2. Ahora, el volumen total

In [61]:
# Volumen total
#SUMA
volumenes.sum()

np.float64(61257.91515234737)

In [62]:
sum(volumenes)

np.float64(61257.91515234737)

3. ¿Cuál contenedor puede almacenar más volumen? ¿Cuánto?

In [63]:
# Contenedor que puede almacenar más volumen
volumenes.max()

np.float64(27646.01535159018)

In [69]:
# También se puede, pero no es recomendable. Ver comparación de tiempos
volumenes

array([ 4241.15008235,   549.77871438, 20882.16636841,  7938.80463562,
       27646.01535159])

In [ ]:
volumenes.argmax() #Índice del contenedor con mayor volumen

np.int64(4)

4. ¿Cuál contenedor puede almacenar menos volumen? ¿Cuánto?

In [68]:
volumenes.min()

np.float64(549.7787143782139)

In [67]:
# Contenedor que puede almacenar menos volumen
volumenes.argmin() #Índice del contenedor con menor volumen

np.int64(1)

5. Media, mediana y desviación estándar de los volúmenes

In [83]:
# Media, mediana y desviación estándar
volumenes.mean(), volumenes.std(), np.median(volumenes)

(np.float64(12251.583030469474),
 np.float64(10307.034811178866),
 np.float64(7938.804635621406))

In [72]:
# Atributos shape y dtype
help(volumenes.reshape)

Help on built-in function reshape:

reshape(*shape, order='C', copy=None) method of numpy.ndarray instance
    a.reshape(shape, /, *, order='C', copy=None)
    a.reshape(*shape, order='C', copy=None)

    Returns an array containing the same data with a new shape.

    Refer to `numpy.reshape` for full documentation.

    See Also
    --------
    numpy.reshape : equivalent function

    Notes
    -----
    Unlike the free function `numpy.reshape`, this method on `ndarray` allows
    the elements of the shape parameter to be passed in as separate arguments.
    For example, ``a.reshape(4, 2)`` is equivalent to ``a.reshape((4, 2))``.



## 1.2 Trabajando con matrices

### Problema 2

> 25 cartas numeradas de la 1 a la 25 se distribuyen aleatoriamente y en partes iguales a 5 personas. Encuentre la suma de cartas para cada persona tal que: 
> - para la primera persona, la suma es el valor de la primera carta menos la suma del resto de las cartas;
> - para la segunda persona, la suma es el valor de la segunda carta menos la suma del resto de las cartas;
> - y así sucesivamente ...

> La persona para la cual la suma sea mayor, será el ganador. Encontrar el ganador.

Lo primero será generar los números del 1 al 25. ¿Cómo podemos hacer esto?

np.arange = np.array(range)

In [122]:
# Ayuda en la función np.arange()
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None, *, like=None)

    Return evenly spaced values within a given interval.

    ``arange`` can be called with a varying number of positional arguments:

    * ``arange(stop)``: Values are generated within the half-open interval
      ``[0, stop)`` (in other words, the interval including `start` but
      excluding `stop`).
    * ``arange(start, stop)``: Values are generated within the half-open
      interval ``[start, stop)``.
    * ``arange(start, stop, step)`` Values are generated within the half-open
      interval ``[start, stop)``, with spacing between values given by
      ``step``.

    For integer arguments the function is roughly equivalent to the Python
    built-in :py:class:`range`, but returns an ndarray rather than a ``range``
    instance.

    When using a non-integer step, such as 0.1, it is often better to use
    `numpy.linspace`.

    See the Warning sections 

In [96]:
# Números del 1 al 25
cartas=np.arange(1,26)
cartas

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [97]:
np.array(range(1,26))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

Luego, tal y como en un juego de cartas, deberíamos barajarlos, antes de repartirlos:

In [88]:
# Ayuda en la función np.random.shuffle()
help(np.random.shuffle)

Help on method shuffle in module numpy.random:

shuffle(x) method of numpy.random.mtrand.RandomState instance
    shuffle(x)

    Modify a sequence in-place by shuffling its contents.

    This function only shuffles the array along the first axis of a
    multi-dimensional array. The order of sub-arrays is changed but
    their contents remains the same.

    .. note::
        New code should use the `~numpy.random.Generator.shuffle`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    x : ndarray or MutableSequence
        The array, list or mutable sequence to be shuffled.

    Returns
    -------
    None

    See Also
    --------
    random.Generator.shuffle: which should be used for new code.

    Examples
    --------
    >>> arr = np.arange(10)
    >>> np.random.shuffle(arr)
    >>> arr
    [1 7 5 2 9 4 3 6 0 8] # random

    Multi-dimensional arrays are only shuffled along the firs

In [98]:
# Barajar
np.random.shuffle(cartas)

In [99]:
# Ver valores
cartas

array([25, 10, 11, 17, 16, 22, 20,  8, 12, 24, 19,  5, 23,  9,  6, 14, 13,
        1,  3,  4, 18, 15, 21,  7,  2])

Bien. Ahora, deberíamos distribuir las cartas. Podemos imaginarnos la distribución como una matriz 5x5:

In [100]:
# Repartir cartas
cartas = cartas.reshape((5,5))

In [101]:
# Ver valores
cartas

array([[25, 10, 11, 17, 16],
       [22, 20,  8, 12, 24],
       [19,  5, 23,  9,  6],
       [14, 13,  1,  3,  4],
       [18, 15, 21,  7,  2]])

In [102]:
cartas[0,:] # Primera fila

array([25, 10, 11, 17, 16])

In [103]:
cp1 = cartas[0,0] - np.sum(cartas[0,:])
cp1

np.int64(-54)

In [104]:
cartas[1,1]

np.int64(20)

In [106]:
cp2 = cartas[1,1] - (cartas[1,0] + np.sum(cartas[1,2:]))
cp2

np.int64(-46)

Entonces, tenemos 5 cartas para cada una de las 5 personas, visualizadas como una matriz 5x5.

Lo único que nos falta es encontrar la suma para cada uno, es decir, sumar el elemento de la diagonal principal y restar las demás entradas de la fila (o columna).

¿Cómo hacemos esto?

In [ ]:
# Ayuda en la función np.eye()
# MATRIZ IDENTIDAD (ES CUADRADA)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Matriz con la diagonal principal
#  NO ES MULTIPLICACIÓN DE MATRICES, ES MULTIPLICACIÓN ELEMENTO A ELEMENTO
np.eye(5) * cartas

array([[25.,  0.,  0.,  0.,  0.],
       [ 0., 20.,  0.,  0.,  0.],
       [ 0.,  0., 23.,  0.,  0.],
       [ 0.,  0.,  0.,  3.,  0.],
       [ 0.,  0.,  0.,  0.,  2.]])

In [110]:
#MULTIPLICACIÓN DE MATRICES ES CON np.dot() O CON @ o con np.matmul()
mat_p = np.eye(5) @ cartas
mat_p

array([[25., 10., 11., 17., 16.],
       [22., 20.,  8., 12., 24.],
       [19.,  5., 23.,  9.,  6.],
       [14., 13.,  1.,  3.,  4.],
       [18., 15., 21.,  7.,  2.]])

In [111]:
# Ayuda en la función np.ones()
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, device=None, like=None)
    Return a new array of given shape and type, filled with ones.

    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    device : str, optional
        The device on which to place the created array. Default: None.
        For Array-API interoperability only, so must be ``"cpu"`` if passed.

        .. versionadded:: 2.0.0
    like : array_like, optional
            Reference object to allow the creation of arrays which are not
            NumPy arrays. If an array-like passed in as ``like`` supports
  

In [113]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [114]:
mat_comp = np.ones((5,5)) - np.eye(5)
mat_comp

array([[0., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1.],
       [1., 1., 0., 1., 1.],
       [1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 0.]])

In [116]:
# Matriz con los elementos fuera de la diagonal negativos
mat_comp_cartas = mat_comp * cartas
mat_comp_cartas

array([[ 0., 10., 11., 17., 16.],
       [22.,  0.,  8., 12., 24.],
       [19.,  5.,  0.,  9.,  6.],
       [14., 13.,  1.,  0.,  4.],
       [18., 15., 21.,  7.,  0.]])

In [ ]:
mat_comp_cartas.sum(axis=1) # Suma por filas, 0 sería suma por columnas

array([54., 66., 39., 32., 61.])

In [118]:
# Matriz completa
mat_comp * cartas - np.eye(5) * cartas

array([[-25.,  10.,  11.,  17.,  16.],
       [ 22., -20.,   8.,  12.,  24.],
       [ 19.,   5., -23.,   9.,   6.],
       [ 14.,  13.,   1.,  -3.,   4.],
       [ 18.,  15.,  21.,   7.,  -2.]])

In [119]:
(cartas * np.eye(5) - mat_comp * cartas)

array([[ 25., -10., -11., -17., -16.],
       [-22.,  20.,  -8., -12., -24.],
       [-19.,  -5.,  23.,  -9.,  -6.],
       [-14., -13.,  -1.,   3.,  -4.],
       [-18., -15., -21.,  -7.,   2.]])

In [121]:
# Sumar por filas
r = (cartas * np.eye(5) - mat_comp * cartas).sum(axis=1)
r

array([-29., -46., -16., -29., -59.])

¿Quién es el ganador?

In [122]:
r.argmax()

np.int64(2)

# 2. Algo de álgebra lineal con NumPy

Bueno, ya hemos utilizado NumPy para resolver algunos problemas de juguete. A través de estos problemas, hemos introducido el tipo de objetos que podemos manipular con NumPy, además de varias funcionalidades que podemos utilizar.

Pues bien, este tipo de objetos nos sirven perfectamente para representar vectores y matrices con entradas reales o complejas... si, de las que estudiamos en algún momento en álgebra lineal.

Mejor aún, NumPy nos ofrece un módulo de álgebra lineal para efectuar las operaciones básicas que podríamos necesitar.

Consideremos la siguiente matriz:

In [157]:
A = np.array([[1,0,1],
              [-1,2,4],
              [2,1,1]])
A

array([[ 1,  0,  1],
       [-1,  2,  4],
       [ 2,  1,  1]])

Podemos obtener varios cálculos útiles alrededor de la matriz A:

In [158]:
# Rango de la matriz A


3

In [159]:
# Determinante de la matriz A


-7.000000000000001

In [160]:
# Inversa de la matriz A


array([[ 0.28571429, -0.14285714,  0.28571429],
       [-1.28571429,  0.14285714,  0.71428571],
       [ 0.71428571,  0.14285714, -0.28571429]])

In [ ]:
# BA != AB
# inv(A)A = Ainv(A)

In [161]:
# Potencia de la matriz A
# A.dot(A).dot(A).dot(A).dot(A)


array([[ 1,  0,  1],
       [ 1,  4, 16],
       [ 4,  1,  1]])

In [162]:
#A^2 = AxA


array([[ 3,  1,  2],
       [ 5,  8, 11],
       [ 3,  3,  7]])

In [163]:
# Eigenvalores y eigenvectores de la matriz A det(\lambdaI - A) = 0  ---> raices del polinomio



In [164]:
l

array([-1.25341804,  1.48003063,  3.77338741])

In [166]:
v

array([[ 0.25358082,  0.47881379,  0.15600857],
       [ 0.78049461, -0.84729481,  0.8879505 ],
       [-0.5714236 ,  0.22984529,  0.4326722 ]])

Por otra parte, si tenemos dos vectores:

podemos calcular su producto interno (producto punto)

De la misma manera, podemos calcular la multiplicación de la matriz A por un vector

<div style="background-color:#f9f9f9; border-left:4px solid #000047; padding:10px;">
<b>Tutorial recomendado</b><br>
    
- Les recomiendo este <a href="https://www.freecodecamp.org/news/object-oriented-programming-concepts-21bb035f7260/">tutorial</a>  para que profundicen más en todo lo que pueden hacer con NumPy

</div>

